name: Create release

on:
  push:
    branches:
      - 'release/*'

permissions:
  contents: write

jobs:
  create_tag:
    runs-on: ubuntu-latest
    outputs:
      package_version: ${{ steps.package-info.outputs.version }}

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Get package info
        id: package-info
        uses: codex-team/action-nodejs-package-info@v1.1

      - name: Create Tag if not exists
        uses: actions/github-script@v6
        env:
          TAG: v${{ steps.package-info.outputs.version }}
        with:
          script: |
            const tagName = process.env.TAG;

            try {
              // Check if the tag already exists
              await github.rest.git.getRef({
                owner: context.repo.owner,
                repo: context.repo.repo,
                ref: `tags/${tagName}`
              });
              console.log(`Tag "${tagName}" already exists. Skipping creation.`);
            } catch (error) {
              if (error.status === 404) {
                console.log(`Tag "${tagName}" does not exist. Creating...`);
                await github.rest.git.createRef({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  ref: `refs/tags/${tagName}`,
                  sha: context.sha
                });
              } else {
                throw error;
              }
            }

  release_windows:
    needs: [create_tag]
    runs-on: windows-2019

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Install Node.js and NPM
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'

      - name: Install dependencies
        run: npm install --legacy-peer-deps --no-audit --prefer-offline
        env:
          PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: 1

      - name: Run build app
        run: npm run build:app

      - name: Run package electron app for windows
        run: npm run package:electron-app:win

      - name: Release windows build
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ needs.create_tag.outputs.package_version }}
          files: |
            ./release/out/Offboard Studio Setup ${{ needs.create_tag.outputs.package_version }}.exe

  release_macos:
    needs: [create_tag]
    runs-on: macos-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Install Node.js and NPM
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'

      - name: Install dependencies
        run: npm install --legacy-peer-deps --no-audit --prefer-offline
        env:
          PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: 1

      - name: Run build app
        run: npm run build:app

      - name: Run package electron app for macOS
        run: npm run package:electron-app:mac

      - name: Release macOS build
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ needs.create_tag.outputs.package_version }}
          files: |
            ./release/out/Offboard Studio-${{ needs.create_tag.outputs.package_version }}-arm64-mac.zip
            ./release/out/Offboard Studio-${{ needs.create_tag.outputs.package_version }}-arm64.dmg
            ./release/out/Offboard Studio-${{ needs.create_tag.outputs.package_version }}-mac.zip
            ./release/out/Offboard Studio-${{ needs.create_tag.outputs.package_version }}.dmg
            ./docs/Help-guide.docx
